name: Construire et pousser les images sur DockerHub et mise à jour Infra pour déclencher ArgoCD

on:
  push:
    branches:
      - main

jobs:
  build_and_push: # nom du job
    runs-on: ubuntu-latest
    strategy:
      matrix: # Pour 2 jobs en parallèle (les steps sont executés 2 fois pour frontend et node-api)
        include:
          - name: frontend
            directory: ./frontend # Le sous repertoire Git du code frontend
            image: techopsfr/app-vue-frontend # nom de l'image à créer
          - name: node-api
            directory: ./node-api # Le sous repertoire Git du code node-api
            image: techopsfr/app-vue-nodeapi # nom de l'image à créer
    steps:
      - name: Récupérer le code source
        uses: actions/checkout@v4       
      - name: Obtenir le hash (7 premiers caractères) du dernier commit pour tag images
        run: echo "VERSION=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
      - name: Connexion à DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Contruire et pousser l'image ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
            context: ${{ matrix.directory }}
            file: ${{ matrix.directory }}/Dockerfile
            push: true
            tags: ${{ matrix.image }}:${{ env.VERSION }}

  update_k8s:
    needs: build_and_push # On a besoin de le job build_and_pushait fni de créer les images
    runs-on: ubuntu-latest

    steps:
      - name: Mettre a jour les déploiement k8s
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< "${{ secrets.GH_DEPLOYMENT_KEY }}"
          git clone git@github.com:techops-fr/projet-vue-infra.git
          cd projet-vue-infra/k8s
          NEW_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          sed -i "s|techopsfr/app-vue-frontend\(:[a-zA-Z0-9_.-]*\)\?|techopsfr/app-vue-frontend:${NEW_TAG}|" frontend-deployment.yaml 
          sed -i "s|techopsfr/app-vue-nodeapi\(:[a-zA-Z0-9_.-]*\)\?|techopsfr/app-vue-nodeapi:${NEW_TAG}|" node-api-deployment.yaml
          git config --global user.name "Github Actions"
          git config --global user.email "admin@techops.ovh"
          git add .
          git commit -m "Mise à jour des versions des images dans k8s à $NEW_TAG"
          git push origin main